// <auto-generated />
using System;
using Infobip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infobip.Migrations
{
    [DbContext(typeof(CarpoolDbContext))]
    [Migration("20230520105833_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Infobip.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarType = "Toyota Corolla",
                            Color = "Red",
                            Name = "Toyota Corolla of Alice",
                            NumberSeats = 3,
                            Plate = "ABC-123"
                        },
                        new
                        {
                            Id = 2,
                            CarType = "Ford F-150",
                            Color = "Orange",
                            Name = "Ford F-150 of Bob",
                            NumberSeats = 3,
                            Plate = "DEF-456"
                        },
                        new
                        {
                            Id = 3,
                            CarType = "BMW 3 Series",
                            Color = "Yellow",
                            Name = "BMW 3 Series of Charlie",
                            NumberSeats = 5,
                            Plate = "GHI-789"
                        },
                        new
                        {
                            Id = 4,
                            CarType = "Honda Civic",
                            Color = "Green",
                            Name = "Honda Civic of David",
                            NumberSeats = 4,
                            Plate = "JKL-012"
                        },
                        new
                        {
                            Id = 5,
                            CarType = "Chevrolet Camaro",
                            Color = "Blue",
                            Name = "Chevrolet Camaro of Emma",
                            NumberSeats = 5,
                            Plate = "MNO-345"
                        },
                        new
                        {
                            Id = 6,
                            CarType = "Hyundai Sonata",
                            Color = "Indigo",
                            Name = "Hyundai Sonata of Frank",
                            NumberSeats = 5,
                            Plate = "PQR-678"
                        },
                        new
                        {
                            Id = 7,
                            CarType = "Nissan Altima",
                            Color = "Violet",
                            Name = "Nissan Altima of Grace",
                            NumberSeats = 6,
                            Plate = "STU-901"
                        },
                        new
                        {
                            Id = 8,
                            CarType = "Audi A4",
                            Color = "Black",
                            Name = "Audi A4 of Henry",
                            NumberSeats = 2,
                            Plate = "VWX-234"
                        },
                        new
                        {
                            Id = 9,
                            CarType = "Subaru Outback",
                            Color = "White",
                            Name = "Subaru Outback of Isabel",
                            NumberSeats = 5,
                            Plate = "YZA-567"
                        },
                        new
                        {
                            Id = 10,
                            CarType = "Tesla Model 3",
                            Color = "Gray",
                            Name = "Tesla Model 3 of Jack",
                            NumberSeats = 4,
                            Plate = "BCD-890"
                        });
                });

            modelBuilder.Entity("Infobip.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDriver = true,
                            Name = "Anna Smith"
                        },
                        new
                        {
                            Id = 2,
                            IsDriver = false,
                            Name = "Brian Jones"
                        },
                        new
                        {
                            Id = 3,
                            IsDriver = false,
                            Name = "Chloe Wilson"
                        },
                        new
                        {
                            Id = 4,
                            IsDriver = true,
                            Name = "Daniel Lee"
                        },
                        new
                        {
                            Id = 5,
                            IsDriver = true,
                            Name = "Ella Brown"
                        },
                        new
                        {
                            Id = 6,
                            IsDriver = false,
                            Name = "Felix Garcia"
                        },
                        new
                        {
                            Id = 7,
                            IsDriver = false,
                            Name = "Grace Miller"
                        },
                        new
                        {
                            Id = 8,
                            IsDriver = true,
                            Name = "Harry Johnson"
                        },
                        new
                        {
                            Id = 9,
                            IsDriver = false,
                            Name = "Ivy Davis"
                        },
                        new
                        {
                            Id = 10,
                            IsDriver = false,
                            Name = "James Taylor"
                        },
                        new
                        {
                            Id = 11,
                            IsDriver = true,
                            Name = "Kayla Martin"
                        },
                        new
                        {
                            Id = 12,
                            IsDriver = true,
                            Name = "Leo Thompson"
                        },
                        new
                        {
                            Id = 13,
                            IsDriver = false,
                            Name = "Mia Williams"
                        },
                        new
                        {
                            Id = 14,
                            IsDriver = false,
                            Name = "Noah Rodriguez"
                        },
                        new
                        {
                            Id = 15,
                            IsDriver = false,
                            Name = "Olivia Anderson"
                        },
                        new
                        {
                            Id = 16,
                            IsDriver = true,
                            Name = "Ryan Clark"
                        },
                        new
                        {
                            Id = 17,
                            IsDriver = true,
                            Name = "Sophia Lopez"
                        },
                        new
                        {
                            Id = 18,
                            IsDriver = true,
                            Name = "Tyler Lewis"
                        },
                        new
                        {
                            Id = 19,
                            IsDriver = false,
                            Name = "Zoe Walker"
                        },
                        new
                        {
                            Id = 20,
                            IsDriver = false,
                            Name = "Adam White"
                        },
                        new
                        {
                            Id = 21,
                            IsDriver = false,
                            Name = "Bella Harris"
                        },
                        new
                        {
                            Id = 22,
                            IsDriver = false,
                            Name = "Connor Hall"
                        },
                        new
                        {
                            Id = 23,
                            IsDriver = true,
                            Name = "Emma Young"
                        },
                        new
                        {
                            Id = 24,
                            IsDriver = false,
                            Name = "Liam Allen"
                        },
                        new
                        {
                            Id = 25,
                            IsDriver = false,
                            Name = "Nora King"
                        });
                });

            modelBuilder.Entity("Infobip.Models.TravelPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
